server.port=8084
spring.datasource.url=jdbc:h2:mem:etudiant-db
spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
universite.adresse=ISET, Tunisie
management.endpoints.web.exposure.include=*
